version: "3.9"

services:

  mysql:
    container_name: mysql-Naf
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "!MyStrongPassword"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
  
volumes:
  data:
  mysql: